version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: tmc_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tmc_backend
    env_file:
      - ./.env
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tmc_frontend
    env_file:
      - ./.env
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  db_data:
